### ISSUE TITLE
Discrepancy in images names across CSV files

### ISSUE THREAD

**Issue by TiernonRR** [paninski-lab/lightning-pose#193]
I am trying to use the multiview loss for a non-mirrorred setup. I have two views and I have organized my data directory in the way explained in the documentation. The index for each csv is the relative path to the respective labeled view. I am unable to run the training script, however, as I recieve the following error in the datasets.py script: ImportError: Discrepancy in images names across CSV files! index:0, image frame names:['labeled-data/151618_view0/frame_0000.png', 'labeled-data/151618_view1/frame_0000.png']. I have cross-examined with the documenatation and this naming schema seems consistent with what is required. Please let me know if you require further information. Thank you!

**Comment by themattinthehatt** [comment]
@TiernonRR I took a look at the code [here](https://github.com/danbider/lightning-pose/blob/9ab15144e3d3d04c8d117f514fd1cdda9cc4b0e2/lightning_pose/data/datasets.py#L436) and it looks like the issue is the code is expecting the name to be of the form `img0000.png` instead of `frame_0000.png`. This is a bit silly, and should work out of the box for any naming scheme that is consistent, so I can look into fixing this. However, I'm about half an hour from going on vacation for the rest of the week, so unfortunately I won't be able to get to this soon. So maybe try renaming to the `imgXXXX.png` scheme and see if that works for you.

**Comment by TiernonRR** [comment]
That did the trick. Thank you!
